### ISSUE TITLE
SimpleTimeLine.as is AS3 version

### ISSUE THREAD

**Issue by delcasda** [greensock/GreenSock-AS2#1]
SimpleTimeLine.as is failing when trying to use AS2 reserved word "add" as function name

**Comment by jackdoyle** [comment]
Hm, I can't replicate this at all. Seems to work and compile fine. Can you please post in the forums at http://greensock.com/forums/ and include a sample .FLA that demonstrates the issue? (Don't forget to zip it first).

**Comment by delcasda** [comment]
Hi Jack, I am targeting Flash player 7 due to client limitations. Is there a minimum FP version?

**Comment by jackdoyle** [comment]
Yep, Flash Player 8. Wow, I'm surprised you've got a project that requires FP7 these days. Ouch. Sorry :(
