### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [greensock/GreenSock-AS2#2]
Hi,

Is there any way to get the API documentation that was on your website before?
thanks

**Comment by jackdoyle** [comment]
The AS3 docs are at http://greensock.com/asdocs/

Please note, however, that we haven't actively supported or maintained the ActionScript version of the library for many, many years. You're welcome to use it, of course, but I'd strongly recommend switching to the JavaScript platform. Flash is largely a dead platform, at least on the web. I'm curious - what are you using it for these days?

**Comment by ROBERT-MCDOWELL** [comment]
many thanks Jack! I just don't want to reprogam 13 years of work.
I don't like javascript at all, I lost too much time to maintain it and unfortunately time is precious on this planet.
btw, I'm contributing to 2 nice projects, cheerpX and Ruffle, in webassembly that will put SWF immortal... ;)
Cheers
